name: Code Coverage

on:
  push:
    branches:
      - 8009-investigation
  pull_request:

env:
  ORG_GRADLE_PROJECT_enablePTS: false

permissions:
  contents: read

jobs:
  publish-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - run: |
          download_url="https://github.com/Godin/openjdk-build/releases/download/JDK-8357885-3/jdk-21.0.8-internal_linux-x64_bin-debug.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '21.0.8'
          architecture: x64

      - run: |
          java -version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4

      - name: Generate Coverage Report
        run: ./gradlew --rerun-tasks jacocoMergedReport
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

      - run: ls /tmp/jvm_*
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: debug-output
          path: /tmp/jvm_*
          if-no-files-found: error
